apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app : {{ .Values.replicaSpec.matchLabels.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.containerSpec.port }}
      port: {{ .Values.service.port }}