apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.naeem4265.com                  # Name of the CRD
spec:
  group: naeem4265.com                        # API group
  names:
    kind: Book                                # Kind of the resource
    listKind: BookList
    plural: books                             # Plural form of the resource name
    singular: book                            # Singular form of the resource name
    shortNames:
      - bk                                    # Short name for the resource
  scope: Namespaced                           # Whether the resource is namespaced or cluster-wide
  versions:
    - name: v1                               # Version name
      schema:
        openAPIV3Schema:
          description: Naeem API server
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:                            # Specification of the custom resources
              description: NaeemSpec defines the desired state of NaeemCRD
              x-kubernetes-validations:      # Rules binding
                - rule: "self.minReplicas <= self.replicas"
                  message: "replicas should be greater than or equal to minReplicas."
                - rule: "self.replicas <= self.maxReplicas"
                  message: "replicas should be smaller than or equal to maxReplicas."
              properties:
                container:
                  properties:
                    image:
                      type: string
                    port:
                      format: int32
                      type: integer
                  type: object
                name:
                  type: string
                replicas:
                  format: int32
                  type: integer
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
              type: object
              required:                        # Must required for custom resources
                - container
                - replicas
            status:                              # Sub resources field
              description: NaeemStatus defines the observed state of NaeemCRD
              properties:
                availableReplicas:
                  format: int32
                  type: integer
              type: object
              required:
                 - availableReplicas
          required:
            - spec
      served: true                             # This version is served
      storage: true                            # This version stored